version: '2.1'
services:
  mysql:
    build: mysql
    image: bitlum/exchange-mysql
    container_name: exchange_mysql
    restart: always
    volumes:
      - /tmp/bitlum/exchange/mysql/lib:/var/lib/mysql
  kafka:
    build: kafka
    container_name: exchange_kafka
    restart: always
    image: bitlum/exchange-kafka
    volumes:
      - /tmp/bitlum/exchange/kafka/logs:/var/log/kafka
